version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/farelabs-0.0.1-SNAPSHOT.jar
    - buildspec.yml
    - scripts/*.sh
    - appspec.yml

  discard-paths: yes