name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven  

    - name: Build with Maven
      run: mvn clean install 

    - name: open cmd and execute file
      run:  cd C:\actions-runner\_work\farlabs-demo\farlabs-demo\target
      run:  cmd
      run:  java -jar farelabs-0.0.1-SNAPSHOT.jar

    # - name: Run JAR
    #   run: java -jar target/farelabs-0.0.1-SNAPSHOT.jar 
    
    # - name: Execute
    #   run: java -jar C:\actions-runner\_work\farlabs-demo\farlabs-demo\target\farelabs-0.0.1-SNAPSHOT.jar


#  cmd  /d/action/farlabs-demo/target
